### ISSUE TITLE
Issue with GK4 1.8.1 and J 3.4

### ISSUE THREAD

**Issue by Cyberek** [GavickPro/News-Show-Pro-GK5#269] opened 2015-03-18 14:05 UTC
Seems there is an issue with loading saved json data of the module on fresh J3.4 installation. One of our users submitted that info.
Could you please verify?

"The Load and Save JSon configuration (Basic settings tab) buttons doesn't seem to work, nothing happens on click and a javascript error appears in the Chrome console : 
Uncaught TypeError: undefined is not a function in class.configmanager.js line 36"

(https://www.gavick.com/forums/news-show-pro/json-configuration-and-joomla-3-4-44412)

**Comment by dziudek** [comment] 2015-03-18 14:26
I've prepared a solution for it today :)

https://github.com/GavickPro/News-Show-Pro-GK5/commit/45516eae5af51dd9acb4dccd6d0d0a8b157544e2

It will be released with the next update (I need to fix issue with VM3 cart popup).

**Comment by dziudek** [comment] 2015-03-18 16:00
I've founded few more issues - final solution is available in this file: https://github.com/GavickPro/News-Show-Pro-GK5/blob/J!3.0_compatible/mod_news_pro_gk5/admin/class.configmanager.js

**Comment by Roadsider** [comment] 2015-03-20 20:17
Hate to say it, but this doesn't fix my issue. Also, I can't make some of the settings stick in the control panel. Much of it is unresponsive. For instance, I can't set "keep aspect ratio" on the thumbnails and I can't make the text wrap around the thumbnail images. Much of this is broken.

**Comment by dziudek** [comment] 2015-03-21 06:11
Please try to install v.1.8.2 and clear your browser cache.

**Comment by Roadsider** [comment] 2015-03-21 14:11
Thank you for your attention to this issue, but I’m sorry to say it still doesn’t take. I’m using Chrome. “Keep Aspect Ratio” still doesn’t stick and I can’t load or create new .json files.

**Comment by dziudek** [comment] 2015-03-21 17:31
Please try to use a different browser.

**Comment by Roadsider** [comment] 2015-03-21 17:34
Doesn't work in Safari either. 




I went into the MySQL table for the module and the settings just don't change. 




RG



—

**Comment by dziudek** [comment] 2015-03-22 05:31
Please send me an access to your page and back-end to dziudek[at]gavick[dot]com

**Comment by Roadsider** [comment] 2015-04-03 15:01
I sent you access but I haven't heard from you. The issue is still vexing us.

**Comment by dziudek** [comment] 2015-04-07 05:24
Could you re-send it? Please try send it to dziudek[at]gmail[dot]com

**Closed** 2015-06-19 05:34 UTC
